[package]
name = "test_suite"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
regex = "1.10.6"
thiserror = "1.0.63"
